Repository frosty-dev/ss14, pull requests merged in 2022-12, with the labels that each got.

#1 Update Publish Workflow
  .github/workflows/publish.yml
Labels: No C#, Status: Needs Review

#3 Fix Build Info
  Tools/gen_build_info.py
Labels: No C#, Status: Needs Review

#9 Resoursы eblя
  Content.Server/Afk/AFKSystem.cs
  Content.Shared/CCVar/CCVars.cs
  Resources/Audio/Announcements/aliens.ogg
  Resources/Audio/Announcements/attention.ogg
  Resources/Audio/Announcements/ert_no.ogg
  Resources/Audio/Announcements/ert_yes.ogg
  Resources/Audio/Announcements/gasleak_end.ogg
  Resources/Audio/Announcements/gasleak_start.ogg
  Resources/Audio/Announcements/license.txt
  Resources/Audio/Announcements/meteors_end.ogg
  Resources/Audio/Announcements/meteors_start.ogg
  Resources/Audio/Announcements/outbreak7.ogg
  Resources/Audio/Announcements/power_off.ogg
  Resources/Audio/Announcements/power_on.ogg
  Resources/Audio/Announcements/radiation.ogg
  Resources/Audio/Announcements/sentience.ogg
  Resources/Audio/Announcements/shuttle_dock.ogg
  Resources/Audio/Announcements/shuttlecalled.ogg
  Resources/Audio/Announcements/shuttlerecalled.ogg
  Resources/Audio/Announcements/ventclog.ogg
  Resources/Audio/Announcements/welcome.ogg
  Resources/Locale/en-US/afk/afk.ftl
  Resources/Locale/ru-RU/afk/afk.ftl
Labels: Status: Needs Review

#12 Resourses sex part 2
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/weapons/guns/revolvers/revolvers.ftl
  Resources/Locale/ru-RU/white/round-notifications/notifications.ftl
  Resources/Prototypes/Entities/Structures/Doors/Airlocks/base_structureairlocks.yml
  Resources/Prototypes/Entities/Structures/Walls/walls.yml
  Resources/Prototypes/Entities/Structures/Windows/window.yml
  Resources/Textures/Structures/Machines/microwave.rsi/meta.json
  Resources/Textures/Structures/Piping/Atmospherics/Portable/portable_scrubber.rsi/meta.json
  Resources/Textures/Structures/Storage/tanks.rsi/meta.json
  Resources/Textures/Structures/Wallmounts/air_monitors.rsi/meta.json
  Resources/Textures/Structures/Wallmounts/camera.rsi/meta.json
Labels: No C#, Status: Needs Review

#10 Команда roundid
  Content.Server/Chat/Commands/RoundIdCommand.cs
Labels: Status: Needs Review

#13 красивые аирлоки
  Content.Client/Doors/AirlockVisualizer.cs
  Content.Server/Doors/Components/AirlockComponent.cs
Labels: Status: Needs Review

#16 Урон челюстям жизни (Чуть больше чем у топора, но они медленне бьют).
  Resources/Prototypes/Entities/Objects/Tools/jaws_of_life.yml
  Resources/Prototypes/Entities/Objects/Tools/tools.yml
Labels: No C#, Status: Needs Review

#18 Better chat
  Content.Server/Chat/Systems/ChatSystem.cs
  Content.Server/Humanoid/Components/HumanoidComponent.cs
  Content.Server/Humanoid/Systems/HumanoidSystem.cs
Labels: Status: Needs Review

#20 Fix
  Content.Server/Chat/Systems/ChatSystem.cs
Labels: Status: Needs Review

#21 Chat fix
  Content.Server/Chat/Systems/ChatSystem.cs
  Content.Server/Humanoid/Systems/HumanoidSystem.cs
Labels: Status: Needs Review

#23 up
  Content.Client/Audio/AmbientSoundSystem.cs
  Content.Server/Construction/AnchorableSystem.cs
  Content.Server/Pointing/EntitySystems/PointingSystem.cs
  Content.Server/Power/Pow3r/BatteryRampPegSolver.cs
  Resources/Changelog/Changelog.yml
  Resources/Locale/en-US/prototypes/catalog/research/technologies.ftl
  Resources/Prototypes/Catalog/Research/technologies.yml
  Resources/Prototypes/Entities/Structures/Machines/lathe.yml
Labels: Status: Needs Review

#24 Upstream + Locale + ru crayons
  Content.Client/Audio/AmbientSoundSystem.cs
  Content.Server/Construction/AnchorableSystem.cs
  Content.Server/Pointing/EntitySystems/PointingSystem.cs
  Content.Server/Power/Pow3r/BatteryRampPegSolver.cs
  Resources/Changelog/Changelog.yml
  Resources/Locale/en-US/prototypes/catalog/research/technologies.ftl
  Resources/Locale/ru-RU/atmos/air-alarm-ui.ftl
  Resources/Locale/ru-RU/escape-menu/ui/options-menu.ftl
  Resources/Locale/ru-RU/ghost/roles/ghost-role-component.ftl
  Resources/Locale/ru-RU/interaction/interaction-popup-component.ftl
  Resources/Locale/ru-RU/radiation/geiger-component.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/catalog/fills/boxes/ammunition.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/markers/shuttle.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/markers/spawners/mobs.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/npcs/pets.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/devices/geiger.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/storage/crates/crates.ftl
  Resources/Locale/ru-RU/visual_effects.ftl
  Resources/Prototypes/Catalog/Research/technologies.yml
  Resources/Prototypes/Entities/Structures/Machines/lathe.yml
  Resources/Prototypes/White/Decals/crayons.yml
  Resources/Textures/White/Decals/Effects/crayondecals.rsi/cyr_b.png
  Resources/Textures/White/Decals/Effects/crayondecals.rsi/cyr_c.png
  Resources/Textures/White/Decals/Effects/crayondecals.rsi/cyr_ch.png
  Resources/Textures/White/Decals/Effects/crayondecals.rsi/cyr_d.png
  Resources/Textures/White/Decals/Effects/crayondecals.rsi/cyr_eh.png
  Resources/Textures/White/Decals/Effects/crayondecals.rsi/cyr_f.png
  Resources/Textures/White/Decals/Effects/crayondecals.rsi/cyr_g.png
  Resources/Textures/White/Decals/Effects/crayondecals.rsi/cyr_hard_sign.png
  Resources/Textures/White/Decals/Effects/crayondecals.rsi/cyr_i.png
  Resources/Textures/White/Decals/Effects/crayondecals.rsi/cyr_l.png
  Resources/Textures/White/Decals/Effects/crayondecals.rsi/cyr_p.png
  Resources/Textures/White/Decals/Effects/crayondecals.rsi/cyr_sh.png
  Resources/Textures/White/Decals/Effects/crayondecals.rsi/cyr_shh.png
  Resources/Textures/White/Decals/Effects/crayondecals.rsi/cyr_soft_sign.png
  Resources/Textures/White/Decals/Effects/crayondecals.rsi/cyr_u.png
  Resources/Textures/White/Decals/Effects/crayondecals.rsi/cyr_y.png
  Resources/Textures/White/Decals/Effects/crayondecals.rsi/cyr_ya.png
  Resources/Textures/White/Decals/Effects/crayondecals.rsi/cyr_z.png
  Resources/Textures/White/Decals/Effects/crayondecals.rsi/cyr_zh.png
  Resources/Textures/White/Decals/Effects/crayondecals.rsi/meta.json
Labels: Status: Needs Review, Changes: Sprites

#7 шизофазия
  Content.Client/IoC/ClientContentIoC.cs
  Content.Client/White/Trail/TrailComponent.cs
  Content.Client/White/Trail/TrailLine.cs
  Content.Client/White/Trail/TrailOverlay.cs
  Content.Client/White/Trail/TrailSystem.cs
  Content.Server/White/Trail/TrailComponent.cs
  Content.Server/White/Trail/TrailSystem.cs
  Content.Shared/White/Line/ILine.cs
  Content.Shared/White/Line/ILineManager.cs
  Content.Shared/White/MathsLambdaParser/MathsLambdaParser.cs
  Content.Shared/White/Trail/SharedTrailComponent.cs
  Content.Shared/White/Trail/TrailSettings.cs
  Resources/Prototypes/White/Entities/Objects/Weapons/Guns/Ammunition/Cartridges/magnum.yml
  Resources/Prototypes/White/Entities/Objects/Weapons/Guns/Ammunition/Magazines/magnum.yml
  Resources/Prototypes/White/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/magnum.yml
  Resources/Textures/White/Effects/Trails/susTrail.png
  Resources/Textures/White/Effects/Trails/trail.png
Labels: Status: Needs Review

#41 loc-fix
  Content.Server/Decals/DecalSystem.cs
  Resources/Locale/en-US/ss14-ru/prototypes/entities/structures/machines/fax_machine.ftl
  Resources/Locale/ru-RU/fax/fax.ftl
  Resources/Locale/ru-RU/nuke/nuke-component.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/machines/fax_machine.ftl
  Resources/Locale/ru-RU/verbs/verb-system.ftl
  Resources/Maps/centcomm.yml
Labels: Status: Needs Review, Changes: Map

#44 Add some extra ALogs
  Content.Server/Cloning/CloningSystem.cs
  Content.Server/Mind/Mind.cs
  Content.Server/Mind/MindSystem.cs
  Content.Server/MobState/MobStateSystem.Crit.cs
  Content.Server/MobState/MobStateSystem.Dead.cs
  Content.Server/MobState/MobStateSystem.cs
Labels: Status: Needs Review

#47 Added kick option to ban Command
  Content.Client/Administration/UI/Tabs/AdminTab/BanWindow.xaml
  Content.Client/Administration/UI/Tabs/AdminTab/BanWindow.xaml.cs
  Content.Server/Administration/Commands/BanCommand.cs
Labels: Status: Needs Review, Changes: UI

#48 Force say
  Content.Server/Administration/Systems/AdminVerbSystem.Tools.cs
  Resources/Locale/en-US/administration/smites.ftl
  Resources/Locale/ru-RU/administration/smites.ftl
  Resources/Textures/Interface/AdminActions/force_say.png
Labels: Status: Needs Review

#50 Upstream
  Content.Client/DragDrop/DragDropSystem.cs
  Content.Client/Outline/TargetOutlineSystem.cs
  Content.Client/Weapons/Ranged/Systems/TetherGunSystem.cs
  Content.Server/Chat/SuicideSystem.cs
  Content.Server/Construction/Conditions/ComponentInTile.cs
  Content.Server/Electrocution/ElectrocutionSystem.cs
  Content.Server/NPC/Components/NPCRVOComponent.cs
  Content.Server/NPC/NPCBlackboard.cs
  Content.Server/NPC/NPCBlackboardSerializer.cs
  Content.Server/NPC/Systems/NPCSteeringSystem.Avoidance.cs
  Content.Server/NPC/Systems/NPCSteeringSystem.Context.cs
  Content.Server/NPC/Systems/NPCSteeringSystem.Obstacles.cs
  Content.Server/NPC/Systems/NPCSteeringSystem.cs
  Content.Server/Radio/EntitySystems/RadioDeviceSystem.cs
  Content.Server/Revenant/EntitySystems/RevenantSystem.Abilities.cs
  Content.Shared/CCVar/CCVars.cs
  Content.Shared/Construction/Conditions/EmptyOrWindowValidInTile.cs
  Content.Shared/Construction/Conditions/NoWindowsInTile.cs
  Content.Shared/Maps/TurfHelpers.cs
  Content.Shared/Radio/RadioVisuals.cs
  Resources/Changelog/Changelog.yml
  Resources/Prototypes/Entities/Structures/Wallmounts/intercom.yml
  Resources/Textures/Structures/Wallmounts/intercom.rsi/broadcasting.png
  Resources/Textures/Structures/Wallmounts/intercom.rsi/meta.json
  Resources/Textures/Structures/Wallmounts/intercom.rsi/unshaded.png
Labels: Status: Needs Review, Changes: Sprites

#49 little-suits
  Resources/Prototypes/Entities/Clothing/OuterClothing/base_clothingouter.yml
Labels: No C#, Status: Needs Review

#53 Sleeping while cloning
  Content.Server/Cloning/CloningSystem.cs
Labels: Status: Needs Review

#52 fix walls and windows sprites
  Resources/Textures/Structures/Walls/solid.rsi/reinf_over1.png
  Resources/Textures/Structures/Walls/solid.rsi/reinf_over3.png
  Resources/Textures/Structures/Walls/solid.rsi/reinf_over4.png
  Resources/Textures/Structures/Walls/solid.rsi/reinf_over6.png
  Resources/Textures/Structures/Walls/solid.rsi/reinf_over7.png
  Resources/Textures/Structures/Walls/solid.rsi/solid1.png
  Resources/Textures/Structures/Walls/solid.rsi/solid3.png
  Resources/Textures/Structures/Walls/solid.rsi/solid4.png
  Resources/Textures/Structures/Walls/solid.rsi/solid6.png
  Resources/Textures/Structures/Walls/solid.rsi/solid7.png
  Resources/Textures/Structures/Windows/reinforced_plasma_window.rsi/rpwindow1.png
  Resources/Textures/Structures/Windows/reinforced_plasma_window.rsi/rpwindow3.png
  Resources/Textures/Structures/Windows/reinforced_plasma_window.rsi/rpwindow4.png
  Resources/Textures/Structures/Windows/reinforced_plasma_window.rsi/rpwindow6.png
  Resources/Textures/Structures/Windows/reinforced_plasma_window.rsi/rpwindow7.png
  Resources/Textures/Structures/Windows/reinforced_window.rsi/rwindow1.png
  Resources/Textures/Structures/Windows/reinforced_window.rsi/rwindow3.png
  Resources/Textures/Structures/Windows/reinforced_window.rsi/rwindow4.png
  Resources/Textures/Structures/Windows/reinforced_window.rsi/rwindow6.png
  Resources/Textures/Structures/Windows/reinforced_window.rsi/rwindow7.png
Labels: No C#, Status: Needs Review, Changes: Sprites

#54 Prison hardsuit
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/head/hardsuit-helmets.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/outerclothing/hardsuits.ftl
  Resources/Prototypes/Catalog/Fills/Lockers/wardrobe_job.yml
  Resources/Prototypes/Entities/Clothing/Head/hardsuit-helmets.yml
  Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
  Resources/Textures/Clothing/Head/Hardsuits/prisoner.rsi/meta.json
  Resources/Textures/Clothing/OuterClothing/Hardsuits/evaprisoner.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/Clothing/OuterClothing/Hardsuits/evaprisoner.rsi/icon.png
  Resources/Textures/Clothing/OuterClothing/Hardsuits/evaprisoner.rsi/inhand-left.png
  Resources/Textures/Clothing/OuterClothing/Hardsuits/evaprisoner.rsi/inhand-right.png
  Resources/Textures/Clothing/OuterClothing/Hardsuits/prisoner.rsi/meta.json
Labels: No C#, Status: Needs Review, Changes: Sprites

#56 Job ban UI
  Content.Client/Administration/UI/Tabs/AdminTab/AdminTab.xaml
  Content.Client/Administration/UI/Tabs/AdminTab/RoleBanWindow.xaml
  Content.Client/Administration/UI/Tabs/AdminTab/RoleBanWindow.xaml.cs
  Resources/Locale/ru-RU/administration/ui/tabs/admin-tab/player-actions-window.ftl
Labels: Status: Needs Review, Changes: UI

#61 Фиксим допуски
  Content.Client/Administration/UI/Tabs/AdminTab/AdminTab.xaml
Labels: No C#, Status: Needs Review, Changes: UI

#64 shit
  Resources/Audio/Misc/bandits.ogg
Labels: No C#, Status: Needs Review

#66 Sockets
  Content.Server/Content.Server.csproj
  Content.Server/Entry/EntryPoint.cs
  Content.Server/IoC/ServerContentIoC.cs
  Content.Server/UtkaIntegration/Commands/IUtkaCommand.cs
  Content.Server/UtkaIntegration/Commands/UtkaSendOOCMessage.cs
  Content.Server/UtkaIntegration/UtkaCommunication.cs
  Content.Server/UtkaIntegration/UtkaSocket.cs
  Content.Server/UtkaIntegration/UtkaSocketWrapper.cs
  Content.Shared/CCVar/CCVars.cs
Labels: Status: Needs Review

#67 Revert "Sockets (#66)"
  Content.Server/Content.Server.csproj
  Content.Server/Entry/EntryPoint.cs
  Content.Server/IoC/ServerContentIoC.cs
  Content.Server/UtkaIntegration/Commands/IUtkaCommand.cs
  Content.Server/UtkaIntegration/Commands/UtkaSendOOCMessage.cs
  Content.Server/UtkaIntegration/UtkaCommunication.cs
  Content.Server/UtkaIntegration/UtkaSocket.cs
  Content.Server/UtkaIntegration/UtkaSocketWrapper.cs
  Content.Shared/CCVar/CCVars.cs
Labels: Status: Needs Review

#68 did some real things
  .github/workflows/publish.yml
  Tools/gen_build_info.py
Labels: No C#, Status: Needs Review

#69 Угнетение ньюфагов нормальными названиями
  Resources/Locale/ru-RU/administration/commands/add-uplink-command.ftl
  Resources/Locale/ru-RU/devices/device-network.ftl
  Resources/Locale/ru-RU/game-ticking/game-presets/preset-traitor.ftl
  Resources/Locale/ru-RU/job/job-names.ftl
  Resources/Locale/ru-RU/pda/pda-component.ftl
  Resources/Locale/ru-RU/prototypes/catalog/fills/crates/service-crates.ftl
  Resources/Locale/ru-RU/rcd/components/rcd-ammo-component.ftl
  Resources/Locale/ru-RU/rcd/components/rcd-component.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/catalog/fills/boxes/general.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/catalog/fills/crates/service.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/ears/headsets.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/ears/specific.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/devices/holoprojectors.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/devices/pda.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/misc/identification_cards.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/tools/tools.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/machines/vending_machines.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/wallmounts/signs/posters.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/white/entities/objects/devices/pda.ftl
Labels: No C#, Status: Needs Review

#72 Линкор "Clear Sky"
  Resources/Maps/Shuttles/clearskykreiser
Labels: No C#

#71 Иконка ассистента
  Resources/Textures/Interface/Misc/job_icons.rsi/Passenger.png
Labels: No C#, Status: Needs Review, Changes: Sprites

#74 Fixed mb
  Content.Server/UtkaIntegration/UtkaSocket.cs
  Content.Server/UtkaIntegration/UtkaSocketWrapper.cs
Labels: Status: Needs Review

#76 Yes
  Content.Server/UtkaIntegration/UtkaSocket.cs
Labels: Status: Needs Review

#77 Dies from cringe
  Content.Server/Chat/Managers/ChatManager.cs
  Content.Server/UtkaIntegration/Commands/UtkaSendOOCMessage.cs
  Content.Server/UtkaIntegration/UtkaSocket.cs
  Content.Shared/CCVar/CCVars.cs
Labels: Status: Needs Review

#78 ну и зачем блять(
  Resources/Prototypes/Species/diona.yml
  Resources/Prototypes/Species/reptilian.yml
  Resources/Prototypes/Species/slime.yml
Labels: No C#

#80 SetGlobalZoomCommand
  Content.Server/Events/Commands/SetGlobalZoomCommand.cs
Labels: Status: Needs Review

#82 lobbyscreen
  Resources/Prototypes/lobbyscreens.yml
  Resources/Textures/LobbyScreens/papizi.png
  Resources/Textures/LobbyScreens/papizi.png.yml
Labels: No C#, Status: Needs Review

#83 lets fix it arleady
  Content.Server/GameTicking/GameTicker.RoundFlow.cs
  Content.Server/White/DiscordShit/RoundEndedEvent.cs
  Content.Server/White/DiscordShit/RoundNotificationsSystem.cs
  Content.Server/White/DiscordShit/RoundStartedEvent.cs
  Content.Shared/CCVar/CCVars.cs
  Content.Shared/GameTicking/RoundStartedEvent.cs
Labels: Status: Needs Review

#81 Add Fun
  Content.Server/GameTicking/Rules/Configurations/NukeopsRuleConfiguration.cs
  Content.Shared/CCVar/CCVars.cs
  Resources/Audio/PedalEvents/a-howdy-doody-christmas.ogg
  Resources/Audio/PedalEvents/deanMartin-blue-christmas.ogg
  Resources/Audio/PedalEvents/deanMartin-let-Iet-snow.ogg
  Resources/Audio/PedalEvents/deck-the-halls-instrumental.ogg
  Resources/Audio/PedalEvents/doom-enternal-ost.ogg
  Resources/Audio/PedalEvents/leto-i-arbaleti.ogg
  Resources/Audio/PedalEvents/nys-sad-auld-lang-syne.ogg
  Resources/Audio/PedalEvents/space-station-13-code-epsilon.ogg
  Resources/Audio/PedalEvents/steklovata-novyigod.ogg
  Resources/Prototypes/Maps/bagel.yml
  Resources/Prototypes/Maps/box.yml
  Resources/Prototypes/Maps/centcomm.yml
  Resources/Prototypes/Maps/kettle.yml
  Resources/Prototypes/Maps/marathon.yml
  Resources/Prototypes/Maps/origin.yml
  Resources/Prototypes/Roles/Jobs/Cargo/quartermaster.yml
  Resources/Prototypes/Roles/Jobs/Civilian/lawyer.yml
  Resources/Prototypes/Roles/Jobs/Civilian/service_worker.yml
  Resources/Prototypes/Roles/Jobs/Command/head_of_personnel.yml
  Resources/Prototypes/Roles/Jobs/Engineering/atmospheric_technician.yml
  Resources/Prototypes/Roles/Jobs/Engineering/chief_engineer.yml
  Resources/Prototypes/Roles/Jobs/Engineering/technical_assistant.yml
  Resources/Prototypes/Roles/Jobs/Medical/chief_medical_officer.yml
  Resources/Prototypes/Roles/Jobs/Medical/medical_intern.yml
  Resources/Prototypes/Roles/Jobs/Science/research_director.yml
Labels: Status: Needs Review, Changes: Map

#84 Перевод
  Resources/Locale/ru-RU/job/department-desc.ftl
  Resources/Locale/ru-RU/job/job-description.ftl
Labels: No C#, Status: Needs Review

#85 fix govna
  Resources/Locale/ru-RU/job/job-names.ftl
Labels: No C#, Status: Needs Review

#86 Trenny coding
  Content.Client/Clothing/Overlays/HelmetOverlay.cs
  Content.Client/MainMenu/BackgroundControl.cs
  Content.Client/Options/UI/Tabs/GraphicsTab.xaml
  Content.Client/Options/UI/Tabs/GraphicsTab.xaml.cs
  Content.Client/SurveillanceCamera/UI/SurveillanceCameraMonitorViewport.cs
  Content.Client/SurveillanceCamera/UI/SurveillanceCameraMonitorWindow.xaml
  Content.Shared/CCVar/CCVars.cs
  Resources/Prototypes/Shaders/shaders.yml
  Resources/Textures/Shaders/crt.swsl
  Resources/Textures/Shaders/crt2.swsl
Labels: Status: Needs Review, Changes: UI
