Repository frosty-dev/ss14, pull requests merged in 2023-01, with the labels that each got.

#89 Upstream Merge
  Content.Client/Audio/AmbientSoundSystem.cs
  Content.Client/Construction/MachineFrameVisualizer.cs
  Content.Client/Fluids/PuddleVisualizerSystem.cs
  Content.Client/Popups/PopupOverlay.cs
  Content.Client/Popups/PopupSystem.cs
  Content.Client/Shuttles/UI/DockingControl.cs
  Content.Client/Shuttles/UI/RadarConsoleWindow.xaml
  Content.Client/Shuttles/UI/RadarControl.cs
  Content.Client/Shuttles/UI/ShuttleConsoleWindow.xaml
  Content.Server/Atmos/Piping/Unary/EntitySystems/GasCanisterSystem.cs
  Content.Server/Audio/AmbientSoundSystem.cs
  Content.Server/Body/Components/BloodstreamComponent.cs
  Content.Server/Buckle/Systems/BuckleSystem.Buckle.cs
  Content.Server/Cargo/Systems/CargoSystem.Shuttle.cs
  Content.Server/Chat/Systems/ChatSystem.Radio.cs
  Content.Server/Chemistry/EntitySystems/SolutionContainerSystem.cs
  Content.Server/Construction/MachineFrameSystem.cs
  Content.Server/CrewManifest/CrewManifestSystem.cs
  Content.Server/Fluids/Components/AbsorbentComponent.cs
  Content.Server/Fluids/EntitySystems/EvaporationSystem.cs
  Content.Server/Fluids/EntitySystems/MoppingSystem.cs
  Content.Server/Fluids/EntitySystems/PuddleSystem.cs
  Content.Server/Medical/CryoPodSystem.cs
  Content.Server/Radio/Components/HeadsetComponent.cs
  Content.Server/Shuttles/Systems/ShuttleSystem.EmergencyShuttle.cs
  Content.Server/Xenoarchaeology/XenoArtifacts/ArtifactSystem.Nodes.cs
  Content.Server/Xenoarchaeology/XenoArtifacts/ArtifactSystem.cs
  Content.Server/Xenoarchaeology/XenoArtifacts/Effects/Components/ChargeBatteryArtifactComponent.cs
  Content.Server/Xenoarchaeology/XenoArtifacts/Effects/Components/SpawnArtifactComponent.cs
  Content.Server/Xenoarchaeology/XenoArtifacts/Effects/Systems/ChargeBatteryArtifactSystem.cs
  Content.Server/Xenoarchaeology/XenoArtifacts/Effects/Systems/RandomInstrumentArtifactSystem.cs
  Content.Server/Xenoarchaeology/XenoArtifacts/Effects/Systems/SpawnArtifactSystem.cs
  Content.Shared/Construction/MachineFrameVisuals.cs
  Content.Shared/Stacks/SharedStackSystem.cs
  Content.Shared/StepTrigger/Systems/StepTriggerSystem.cs
  Resources/Changelog/Changelog.yml
  Resources/Locale/en-US/construction/conditions/machine-frame-complete.ftl
  Resources/Locale/en-US/reagents/meta/physical-desc.ftl
  Resources/Locale/en-US/xenoarchaeology/artifact-hints.ftl
  Resources/Locale/en-US/xenoarchaeology/misc-artifact.ftl
  Resources/Maps/cluster.yml
  Resources/Maps/meta.yml
  Resources/Prototypes/Entities/Clothing/Ears/headsets.yml
  Resources/Prototypes/Entities/Clothing/Ears/headsets_alt.yml
  Resources/Prototypes/Entities/Effects/puddle.yml
  Resources/Prototypes/Entities/Objects/Consumable/Food/egg.yml
  Resources/Prototypes/Entities/Objects/Consumable/Food/ingredients.yml
  Resources/Prototypes/Entities/Objects/Consumable/Food/produce.yml
  Resources/Prototypes/Entities/Objects/Specific/Xenoarchaeology/item_artifacts.yml
  Resources/Prototypes/Entities/Objects/Specific/Xenoarchaeology/structure_artifacts.yml
  Resources/Prototypes/Entities/Objects/Tools/flashlights.yml
  Resources/Prototypes/Entities/Structures/Machines/frame.yml
  Resources/Prototypes/Entities/Structures/Storage/Canisters/gas_canisters.yml
  Resources/Prototypes/Entities/Structures/Storage/Closets/big_boxes.yml
  Resources/Prototypes/Maps/Pools/default.yml
  Resources/Prototypes/Maps/meta.yml
  Resources/Prototypes/Recipes/Construction/Graphs/machines/machine.yml
  Resources/Prototypes/Recipes/Lathes/misc.yml
  Resources/Prototypes/XenoArch/Effects/normal_effects.yml
  Resources/Prototypes/XenoArch/Effects/utility_effects.yml
Labels: Status: Needs Review, Changes: Map, Changes: UI

#90 Revert "Upstream Merge"
  Content.Client/Audio/AmbientSoundSystem.cs
  Content.Client/Construction/MachineFrameVisualizer.cs
  Content.Client/Fluids/PuddleVisualizerSystem.cs
  Content.Client/Popups/PopupOverlay.cs
  Content.Client/Popups/PopupSystem.cs
  Content.Client/Shuttles/UI/DockingControl.cs
  Content.Client/Shuttles/UI/RadarConsoleWindow.xaml
  Content.Client/Shuttles/UI/RadarControl.cs
  Content.Client/Shuttles/UI/ShuttleConsoleWindow.xaml
  Content.Server/Atmos/Piping/Unary/EntitySystems/GasCanisterSystem.cs
  Content.Server/Audio/AmbientSoundSystem.cs
  Content.Server/Body/Components/BloodstreamComponent.cs
  Content.Server/Buckle/Systems/BuckleSystem.Buckle.cs
  Content.Server/Cargo/Systems/CargoSystem.Shuttle.cs
  Content.Server/Chat/Systems/ChatSystem.Radio.cs
  Content.Server/Chemistry/EntitySystems/SolutionContainerSystem.cs
  Content.Server/Construction/MachineFrameSystem.cs
  Content.Server/CrewManifest/CrewManifestSystem.cs
  Content.Server/Fluids/Components/AbsorbentComponent.cs
  Content.Server/Fluids/EntitySystems/EvaporationSystem.cs
  Content.Server/Fluids/EntitySystems/MoppingSystem.cs
  Content.Server/Fluids/EntitySystems/PuddleSystem.cs
  Content.Server/Medical/CryoPodSystem.cs
  Content.Server/Radio/Components/HeadsetComponent.cs
  Content.Server/Shuttles/Systems/ShuttleSystem.EmergencyShuttle.cs
  Content.Server/Xenoarchaeology/XenoArtifacts/ArtifactSystem.Nodes.cs
  Content.Server/Xenoarchaeology/XenoArtifacts/ArtifactSystem.cs
  Content.Server/Xenoarchaeology/XenoArtifacts/Effects/Components/ChargeBatteryArtifactComponent.cs
  Content.Server/Xenoarchaeology/XenoArtifacts/Effects/Components/SpawnArtifactComponent.cs
  Content.Server/Xenoarchaeology/XenoArtifacts/Effects/Systems/ChargeBatteryArtifactSystem.cs
  Content.Server/Xenoarchaeology/XenoArtifacts/Effects/Systems/RandomInstrumentArtifactSystem.cs
  Content.Server/Xenoarchaeology/XenoArtifacts/Effects/Systems/SpawnArtifactSystem.cs
  Content.Shared/Construction/MachineFrameVisuals.cs
  Content.Shared/Stacks/SharedStackSystem.cs
  Content.Shared/StepTrigger/Systems/StepTriggerSystem.cs
  Resources/Changelog/Changelog.yml
  Resources/Locale/en-US/construction/conditions/machine-frame-complete.ftl
  Resources/Locale/en-US/reagents/meta/physical-desc.ftl
  Resources/Locale/en-US/xenoarchaeology/artifact-hints.ftl
  Resources/Locale/en-US/xenoarchaeology/misc-artifact.ftl
  Resources/Maps/cluster.yml
  Resources/Maps/meta.yml
  Resources/Prototypes/Entities/Clothing/Ears/headsets.yml
  Resources/Prototypes/Entities/Clothing/Ears/headsets_alt.yml
  Resources/Prototypes/Entities/Effects/puddle.yml
  Resources/Prototypes/Entities/Objects/Consumable/Food/egg.yml
  Resources/Prototypes/Entities/Objects/Consumable/Food/ingredients.yml
  Resources/Prototypes/Entities/Objects/Consumable/Food/produce.yml
  Resources/Prototypes/Entities/Objects/Specific/Xenoarchaeology/item_artifacts.yml
  Resources/Prototypes/Entities/Objects/Specific/Xenoarchaeology/structure_artifacts.yml
  Resources/Prototypes/Entities/Objects/Tools/flashlights.yml
  Resources/Prototypes/Entities/Structures/Machines/frame.yml
  Resources/Prototypes/Entities/Structures/Storage/Canisters/gas_canisters.yml
  Resources/Prototypes/Entities/Structures/Storage/Closets/big_boxes.yml
  Resources/Prototypes/Maps/Pools/default.yml
  Resources/Prototypes/Maps/meta.yml
  Resources/Prototypes/Recipes/Construction/Graphs/machines/machine.yml
  Resources/Prototypes/Recipes/Lathes/misc.yml
  Resources/Prototypes/XenoArch/Effects/normal_effects.yml
  Resources/Prototypes/XenoArch/Effects/utility_effects.yml
Labels: Changes: Map, Changes: UI

#91 Upstream Merge
  Content.Client/Audio/AmbientSoundSystem.cs
  Content.Client/Construction/MachineFrameVisualizer.cs
  Content.Client/Fluids/PuddleVisualizerSystem.cs
  Content.Client/Popups/PopupOverlay.cs
  Content.Client/Popups/PopupSystem.cs
  Content.Client/Shuttles/UI/DockingControl.cs
  Content.Client/Shuttles/UI/RadarConsoleWindow.xaml
  Content.Client/Shuttles/UI/RadarControl.cs
  Content.Client/Shuttles/UI/ShuttleConsoleWindow.xaml
  Content.Server/Atmos/Piping/Unary/EntitySystems/GasCanisterSystem.cs
  Content.Server/Audio/AmbientSoundSystem.cs
  Content.Server/Body/Components/BloodstreamComponent.cs
  Content.Server/Buckle/Systems/BuckleSystem.Buckle.cs
  Content.Server/Cargo/Systems/CargoSystem.Shuttle.cs
  Content.Server/Chat/Systems/ChatSystem.Radio.cs
  Content.Server/Chemistry/EntitySystems/SolutionContainerSystem.cs
  Content.Server/Construction/MachineFrameSystem.cs
  Content.Server/CrewManifest/CrewManifestSystem.cs
  Content.Server/Fluids/Components/AbsorbentComponent.cs
  Content.Server/Fluids/EntitySystems/EvaporationSystem.cs
  Content.Server/Fluids/EntitySystems/MoppingSystem.cs
  Content.Server/Fluids/EntitySystems/PuddleSystem.cs
  Content.Server/Medical/CryoPodSystem.cs
  Content.Server/Radio/Components/HeadsetComponent.cs
  Content.Server/Shuttles/Systems/ShuttleSystem.EmergencyShuttle.cs
  Content.Server/Xenoarchaeology/XenoArtifacts/ArtifactSystem.Nodes.cs
  Content.Server/Xenoarchaeology/XenoArtifacts/ArtifactSystem.cs
  Content.Server/Xenoarchaeology/XenoArtifacts/Effects/Components/ChargeBatteryArtifactComponent.cs
  Content.Server/Xenoarchaeology/XenoArtifacts/Effects/Components/SpawnArtifactComponent.cs
  Content.Server/Xenoarchaeology/XenoArtifacts/Effects/Systems/ChargeBatteryArtifactSystem.cs
  Content.Server/Xenoarchaeology/XenoArtifacts/Effects/Systems/RandomInstrumentArtifactSystem.cs
  Content.Server/Xenoarchaeology/XenoArtifacts/Effects/Systems/SpawnArtifactSystem.cs
  Content.Shared/Construction/MachineFrameVisuals.cs
  Content.Shared/Stacks/SharedStackSystem.cs
  Content.Shared/StepTrigger/Systems/StepTriggerSystem.cs
  Resources/Changelog/Changelog.yml
  Resources/Locale/en-US/construction/conditions/machine-frame-complete.ftl
  Resources/Locale/en-US/reagents/meta/physical-desc.ftl
  Resources/Locale/en-US/xenoarchaeology/artifact-hints.ftl
  Resources/Locale/en-US/xenoarchaeology/misc-artifact.ftl
  Resources/Maps/cluster.yml
  Resources/Maps/meta.yml
  Resources/Prototypes/Entities/Clothing/Ears/headsets.yml
  Resources/Prototypes/Entities/Clothing/Ears/headsets_alt.yml
  Resources/Prototypes/Entities/Effects/puddle.yml
  Resources/Prototypes/Entities/Objects/Consumable/Food/egg.yml
  Resources/Prototypes/Entities/Objects/Consumable/Food/ingredients.yml
  Resources/Prototypes/Entities/Objects/Consumable/Food/produce.yml
  Resources/Prototypes/Entities/Objects/Specific/Xenoarchaeology/item_artifacts.yml
  Resources/Prototypes/Entities/Objects/Specific/Xenoarchaeology/structure_artifacts.yml
  Resources/Prototypes/Entities/Objects/Tools/flashlights.yml
  Resources/Prototypes/Entities/Structures/Machines/frame.yml
  Resources/Prototypes/Entities/Structures/Storage/Canisters/gas_canisters.yml
  Resources/Prototypes/Entities/Structures/Storage/Closets/big_boxes.yml
  Resources/Prototypes/Maps/Pools/default.yml
  Resources/Prototypes/Maps/meta.yml
  Resources/Prototypes/Recipes/Construction/Graphs/machines/machine.yml
  Resources/Prototypes/Recipes/Lathes/misc.yml
  Resources/Prototypes/XenoArch/Effects/normal_effects.yml
  Resources/Prototypes/XenoArch/Effects/utility_effects.yml
Labels: Status: Needs Review, Changes: Map, Changes: UI

#92 Фикс радио
  Resources/Locale/en-US/headset/headset-component.ftl
  Resources/Locale/ru-RU/headset/headset-component.ftl
Labels: No C#, Status: Needs Review

#94 аааааааааааааааааааааааааа
  Resources/Audio/Weapons/Guns/Gunshots/cv-shot.ogg
  Resources/Audio/Weapons/Guns/MagIn/cv-reload.ogg
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/weapons/guns/rifles/rifles.ftl
  Resources/Prototypes/Catalog/uplink_catalog.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/light_rifle.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Rifles/rifles.yml
Labels: No C#, Status: Needs Review

#96 Отключил выживание и поменял мин игроков на событиях
  Resources/Prototypes/GameRules/events.yml
  Resources/Prototypes/round_announcements.yml
  Resources/Prototypes/secret_weights.yml
Labels: No C#, Status: Needs Review

#97 Фикс джетпаков
  Content.Shared/Movement/Systems/SharedJetpackSystem.cs
Labels: Status: Needs Review

#102 Фикс консоли связи
  Content.Server/Communications/CommunicationsConsoleSystem.cs
  Resources/Locale/en-US/communications/communications-console-component.ftl
  Resources/Locale/ru-RU/communications/communications-console-component.ftl
Labels: Status: Needs Review

#103 fun
  Resources/Maps/White/Whitebox.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/clothesmate.yml
  Resources/Prototypes/Catalog/uplink_catalog.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/light_rifle.yml
Labels: No C#, Status: Needs Review

#104 fixes
  Content.Client/Clothing/Overlays/HelmetOverlay.cs
  Content.Client/Shuttles/UI/RadarControl.cs
  Content.Client/Stylesheets/StyleBase.cs
  Content.Client/Stylesheets/StyleNano.cs
  Content.Client/Stylesheets/StyleSpace.cs
  Content.Client/Stylesheets/StylesheetManager.cs
  Content.Server/Shuttles/Systems/RadarConsoleSystem.cs
Labels: Status: Needs Review

#99 Нюкеры получают необходимые компоненты при вербе педали.
  Content.Server/GameTicking/Rules/NukeopsRuleSystem.cs
Labels: Status: Needs Review

#105 if diona nuke or zombie remove pacifism
  Content.Server/GameTicking/Rules/NukeopsRuleSystem.cs
  Content.Server/Zombies/ZombifyOnDeathSystem.cs
  Resources/Prototypes/Entities/Mobs/Player/diona.yml
Labels: Status: Needs Review

#106 Dares features
  Content.Server/Sandbox/SandboxSystem.cs
Labels: Status: Needs Review

#107 add some words to filter.(requsted bu dustin)
  Resources/White/ChatFilters/slang.json
Labels: No C#, Status: Needs Review

#108 Небольшой реворк ивента метеоров
  Content.Server/Explosion/Components/ExplosiveComponent.cs
  Content.Server/Explosion/EntitySystems/ExplosionSystem.cs
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Projectiles/meteors.yml
  Resources/Prototypes/GameRules/events.yml
Labels: Status: Needs Review

#114 whisper system cringers edition
  Content.Server/White/TTS/TTSSystem.Sanitize.cs
  Content.Server/White/TTS/TTSSystem.cs
Labels: Status: Needs Review

#115 Shuttle calling and recalling messages will write about initiator.
  Content.Server/Communications/CommunicationsConsoleSystem.cs
  Content.Server/RoundEnd/RoundEndSystem.cs
  Resources/Locale/en-US/round-end/round-end-system.ftl
  Resources/Locale/ru-RU/round-end/round-end-system.ftl
Labels: Status: Needs Review

#121 CRAFT BORSCHA
  Resources/Prototypes/Recipes/Cooking/meal_recipes.yml
Labels: No C#

#120 tweak for singul. destroyer component. Now check for active
  Content.Server/Singularity/EntitySystems/EventHorizonSystem.cs
Labels: Status: Needs Review

#116 Метеоритный шторм
  Content.Server/Communications/CommunicationsConsoleSystem.cs
  Content.Server/StationEvents/EventManagerSystem.cs
  Content.Server/StationEvents/MeteorStationEventScheduler.cs
  Resources/Locale/en-US/communications/communications-console-component.ftl
  Resources/Locale/en-US/game-ticking/game-presets/preset-survivalmeteor.ftl
  Resources/Locale/en-US/shuttles/emergency.ftl
  Resources/Locale/ru-RU/communications/communications-console-component.ftl
  Resources/Locale/ru-RU/game-ticking/game-presets/preset-survivalmeteor.ftl
  Resources/Locale/ru-RU/shuttles/emergency.ftl
  Resources/Prototypes/GameRules/roundstart.yml
  Resources/Prototypes/game_presets.yml
Labels: Status: Needs Review

#122 Meteor Quick Fix
  Content.Server/StationEvents/MeteorStationEventScheduler.cs
  Resources/Prototypes/game_presets.yml
Labels: Status: Needs Review

#123 Теперь цель станции статична.
  Content.Server/White/StationGoal/StationGoalCommand.cs
  Content.Server/White/StationGoal/StationGoalSystem.cs
  Resources/Locale/en-US/station-goal/station-goal-component.ftl
  Resources/Locale/ru-RU/station-goal/station-goal-component.ftl
  Resources/Prototypes/White/Objectives/goals.yml
Labels: Status: Needs Review

#124 why i have fix this lol
  Content.Server/Humanoid/Systems/HumanoidSystem.cs
  Content.Server/White/TTS/HumanoidSystemTTS.cs
  Content.Server/White/TTS/TTSSystem.Sanitize.cs
  Content.Shared/CCVar/CCVars.cs
  Content.Shared/Humanoid/HumanoidComponent.cs
Labels: Status: Needs Review

#126 sawmil oleg senior master
  Content.Server/GameTicking/Rules/NukeopsRuleSystem.cs
  Content.Server/Zombies/ZombifyOnDeathSystem.cs
  Resources/Maps/White/Whitebox.yml
  Resources/Prototypes/Entities/Mobs/Player/diona.yml
Labels: Status: Needs Review

#128 Disable the auto shuttle by default.
  Content.Shared/CCVar/CCVars.cs
Labels: Status: Needs Review

#131 Fix for meteor preset
  Content.Server/StationEvents/MeteorStationEventScheduler.cs
Labels: Status: Needs Review

#130 Hotfix for secret game mode check if players not enough.
  Content.Server/GameTicking/Rules/Configurations/NukeopsRuleConfiguration.cs
  Content.Server/GameTicking/Rules/NukeopsRuleSystem.cs
  Content.Server/GameTicking/Rules/SecretRuleSystem.cs
  Content.Server/GameTicking/Rules/TraitorRuleSystem.cs
  Content.Server/GameTicking/Rules/ZombieRuleSystem.cs
  Content.Shared/CCVar/CCVars.cs
  Resources/Prototypes/game_presets.yml
Labels: Status: Needs Review

#136 Customvote now shows number of votes for each option
  Content.Server/Voting/VoteCommands.cs
  Resources/Locale/en-US/voting/vote-commands.ftl
  Resources/Locale/ru-RU/voting/vote-commands.ftl
Labels: Status: Needs Review
